### PR TITLE
Use 3rd party package for rendering template blocks

### LINKED ISSUE #28: The subject block cannot be overwrite when inherit the email template.
Is the subject block treated specially and did not get into the Django template inheritance process?
I had to use this work around that is put this in my base.email
{% block subject %}{{ subject }}{% endblock %}

And every time when call send email, the context need to have the subject line.

### LINKED ISSUE #46: Template' object is not iterable
Hi, when I try to send a mail I got 
    ``Template' object is not iterable``

I found in utils.py this part:
    ``for node in template``

but template is not a list. Instead I can fix and get app running if I make something like:

   ``for node in template.template.nodelist:``

It's my problem? Anyone else?

Thanks.

### PR DESCRIPTION
**Pull request by clokep**
This is similar to #38, but actually uses a separate package ([django-render-block](https://pypi.python.org/pypi/django-render-block)). This is based on the snippets used to make [Django-Block-Render](https://github.com/uniphil/Django-Block-Render), but updated and with a lot more features:
* Tests
* Supports Django 1.8/1.9/1.10
* Set up to support more than just Django templates (I have partial support for Jinja2 as well)
* pip installable (and on pypi)

In full disclosure, the `django-render-block` package is mine.

The single test added in this is pretty lame, but I wasn't sure what else to add. Suggestions are welcome! (Note the tests will pass without the change here. :)) If there's a particular behavior you want tested in terms of template inheritance, etc. they'd probably make more sense as part of the [django-render-block repo](https://github.com/clokep/django-render-block).

Fixes #28 
Fixes #46

### CODE REVIEW

**Comment by aericson** [comment]
I'm a bit reluctant to add an external dependency that was last updated 4 years ago and has 7 stars. I look more into this soon.

Thanks for this.

**Comment by clokep** [comment]
4 years ago? I pushed all of this a few months ago. I just updated it for Python 3 a couple of weeks ago...I guess I should update/test it for Django 1.10 though.

**Comment by aericson** [comment]
Sorry, don't think I was clear. I meant using the lib you mentioned https://github.com/uniphil/Django-Block-Render

**Comment by aericson** [comment]
Oh, you have a different version in another repo https://github.com/clokep/django-render-block. I looked up the wrong one.

Thanks. Will take a look.

**Comment by clokep** [comment]
Yeah, I didn't start from that code, but from the original "Django Snippets", then cleaned it up, expanded it, documented it, added tests, etc. Sorry for the similar name!

**Comment by aericson** [comment]
Re-based it and made a few changes, created a new PR #70 for this.

**Pull request closed without merging**
