### PR TITLE
Using django-render-block to render template blocks

### PR DESCRIPTION
**Pull request by aericson**

### CODE REVIEW

**Comment by aericson** [comment]
Tests will not pass until we update django-render-block. Waiting for this https://github.com/clokep/django-render-block/pull/8 to be on pypi before this can be merged.

**Comment by aericson** [comment]
Closes #57

**Comment by clokep** [comment]
@aericson I just pushed version 0.5, that includes the changes you need!

**Comment by aericson** [comment]
@clokep Thanks!

**Pull request merged**
